{
 "title": "Kentik",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Traffic in / out",
   "type": "graph",
   "description": "Outbound traffic is drawn with negative values.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(protocol)(rate(KFlow:in_bytes[$__rate_interval]))",
     "legendFormat": "{{protocol}}-in"
    },
    {
     "expr": "sum by(protocol)(rate(KFlow:out_bytes[$__rate_interval]))",
     "legendFormat": "{{protocol}}-out"
    }
   ]
  },
  {
   "title": "Top Source Packet Regions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum by (src_geo_region) (rate(KFlow:in_pkts[$__rate_interval])))",
     "legendFormat": "{{src_geo_region}}"
    }
   ]
  },
  {
   "title": "Top Source Ports by Packets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum by(l4_src_port)(KFlow:out_pkts_in_pkts))",
     "legendFormat": "{{l4_src_port}}"
    }
   ]
  },
  {
   "title": "Latency p90",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum by (custom_str_src_host)(rate(KFlow:custom_int_APPL_LATENCY_MS[$__rate_interval])))",
     "legendFormat": "{{custom_str_src_host}}"
    }
   ]
  }
 ]
}