{
 "title": "Convis",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(bytes_rx{container_name!=\"\"}, k8s_namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Bytes Received (rx)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (k8s_pod, container_name) (bytes_rx:sum{k8s_namespace=~\"$namespace\", container_name!=\"\"})",
     "legendFormat": "{{k8s_pod}}_{{container_name}}"
    }
   ]
  },
  {
   "title": "Total Bytes Transmitted (tx)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (k8s_pod, container_name) (bytes_tx:sum{k8s_namespace=~\"$namespace\", container_name!=\"\"})",
     "legendFormat": "{{k8s_pod}}_{{container_name}}"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Pod Traffic",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (k8s_pod) (rate(bytes_rx:sum{k8s_namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "{{k8s_pod}} (rx)"
    },
    {
     "expr": "sum by (k8s_pod) (rate(bytes_tx:sum{k8s_namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "{{k8s_pod}} (tx)"
    }
   ]
  },
  {
   "title": "Targets",
   "type": "status-history",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum by (destination_ip) (count without (container_id, container_image, destination_port, source_ip, source_port, process_cmd) (bytes_rx{k8s_namespace=~\"$namespace\", container_name!=\"\", event=\"Close\"}))",
     "legendFormat": "{{destination_ip}}"
    }
   ]
  },
  { "title": "Processes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Process Traffic By Pid (rx)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (container_name, process_pid) (rate(bytes_rx:sum{k8s_namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "{{container_name}} ({{process_pid}})"
    }
   ]
  },
  {
   "title": "Process Traffic By Pid (tx)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (container_name, process_pid) (rate(bytes_tx:sum{k8s_namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "{{container_name}} ({{process_pid}})"
    }
   ]
  },
  { "title": "External", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "External Connections",
   "type": "geomap",
   "gridPos": { "h": 25, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "geo_ip{k8s_namespace=~\"$namespace\"}"
    }
   ]
  }
 ]
}